// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AttachmentsControllerGetAttachmentData, AttachmentsControllerGetAttachmentErrors, AttachmentsControllerGetAttachmentResponses, FoldersControllerListFoldersData, FoldersControllerListFoldersErrors, FoldersControllerListFoldersResponses, FoldersControllerListFoldersV2Data, FoldersControllerListFoldersV2Errors, FoldersControllerListFoldersV2Responses, HealthControllerHealthData, HealthControllerHealthResponses, MailsControllerApplyActionData, MailsControllerApplyActionErrors, MailsControllerApplyActionResponses, MailsControllerApplyBlacklistData, MailsControllerApplyBlacklistErrors, MailsControllerApplyBlacklistResponses, MailsControllerBimiLogoData, MailsControllerBimiLogoErrors, MailsControllerBimiLogoResponses, MailsControllerGetMessageData, MailsControllerGetMessageErrors, MailsControllerGetMessageResponses, MailsControllerListMessagesByFolderData, MailsControllerListMessagesByFolderErrors, MailsControllerListMessagesByFolderResponses, MailsControllerListMessagesData, MailsControllerListMessagesErrors, MailsControllerListMessagesResponses, MailsControllerListSentMessagesData, MailsControllerListSentMessagesErrors, MailsControllerListSentMessagesResponses, MailsControllerMessageActionsData, MailsControllerMessageActionsErrors, MailsControllerMessageActionsResponses, MailsControllerSendMessageData, MailsControllerSendMessageErrors, MailsControllerSendMessageResponses, MailsControllerViewMessageData, MailsControllerViewMessageErrors, MailsControllerViewMessageResponses, UsersControllerAddApnsData, UsersControllerAddApnsErrors, UsersControllerAddApnsResponses, UsersControllerAddBlacklistData, UsersControllerAddBlacklistErrors, UsersControllerAddBlacklistResponses, UsersControllerAddFirebaseData, UsersControllerAddFirebaseErrors, UsersControllerAddFirebaseResponses, UsersControllerUserConfigData, UsersControllerUserConfigErrors, UsersControllerUserConfigResponses, WebhooksControllerSendgridData, WebhooksControllerSendgridResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health check
 */
export const healthControllerHealth = <ThrowOnError extends boolean = false>(options?: Options<HealthControllerHealthData, ThrowOnError>): RequestResult<HealthControllerHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthControllerHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Get the configuration of the authenticated user
 */
export const usersControllerUserConfig = <ThrowOnError extends boolean = false>(options?: Options<UsersControllerUserConfigData, ThrowOnError>): RequestResult<UsersControllerUserConfigResponses, UsersControllerUserConfigErrors, ThrowOnError> => (options?.client ?? client).get<UsersControllerUserConfigResponses, UsersControllerUserConfigErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/userConfig',
    ...options
});

/**
 * Register a Firebase (FCM) device token
 */
export const usersControllerAddFirebase = <ThrowOnError extends boolean = false>(options: Options<UsersControllerAddFirebaseData, ThrowOnError>): RequestResult<UsersControllerAddFirebaseResponses, UsersControllerAddFirebaseErrors, ThrowOnError> => (options.client ?? client).post<UsersControllerAddFirebaseResponses, UsersControllerAddFirebaseErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/addFirebase',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Register an APNS device token
 */
export const usersControllerAddApns = <ThrowOnError extends boolean = false>(options: Options<UsersControllerAddApnsData, ThrowOnError>): RequestResult<UsersControllerAddApnsResponses, UsersControllerAddApnsErrors, ThrowOnError> => (options.client ?? client).post<UsersControllerAddApnsResponses, UsersControllerAddApnsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/addAPNS',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Add an entry to the user mail blacklist
 */
export const usersControllerAddBlacklist = <ThrowOnError extends boolean = false>(options: Options<UsersControllerAddBlacklistData, ThrowOnError>): RequestResult<UsersControllerAddBlacklistResponses, UsersControllerAddBlacklistErrors, ThrowOnError> => (options.client ?? client).put<UsersControllerAddBlacklistResponses, UsersControllerAddBlacklistErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/blacklist',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List received messages of the authenticated user
 */
export const mailsControllerListMessages = <ThrowOnError extends boolean = false>(options?: Options<MailsControllerListMessagesData, ThrowOnError>): RequestResult<MailsControllerListMessagesResponses, MailsControllerListMessagesErrors, ThrowOnError> => (options?.client ?? client).get<MailsControllerListMessagesResponses, MailsControllerListMessagesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/msgs',
    ...options
});

/**
 * List sent messages of the authenticated user
 */
export const mailsControllerListSentMessages = <ThrowOnError extends boolean = false>(options?: Options<MailsControllerListSentMessagesData, ThrowOnError>): RequestResult<MailsControllerListSentMessagesResponses, MailsControllerListSentMessagesErrors, ThrowOnError> => (options?.client ?? client).get<MailsControllerListSentMessagesResponses, MailsControllerListSentMessagesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/msgs/sent',
    ...options
});

/**
 * List received messages by category and folder
 */
export const mailsControllerListMessagesByFolder = <ThrowOnError extends boolean = false>(options: Options<MailsControllerListMessagesByFolderData, ThrowOnError>): RequestResult<MailsControllerListMessagesByFolderResponses, MailsControllerListMessagesByFolderErrors, ThrowOnError> => (options.client ?? client).get<MailsControllerListMessagesByFolderResponses, MailsControllerListMessagesByFolderErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/msgs/{category}/{folder}',
    ...options
});

/**
 * Get a single message
 */
export const mailsControllerGetMessage = <ThrowOnError extends boolean = false>(options: Options<MailsControllerGetMessageData, ThrowOnError>): RequestResult<MailsControllerGetMessageResponses, MailsControllerGetMessageErrors, ThrowOnError> => (options.client ?? client).get<MailsControllerGetMessageResponses, MailsControllerGetMessageErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/msg/{id}',
    ...options
});

/**
 * Render the HTML (or text) body of a message
 */
export const mailsControllerViewMessage = <ThrowOnError extends boolean = false>(options: Options<MailsControllerViewMessageData, ThrowOnError>): RequestResult<MailsControllerViewMessageResponses, MailsControllerViewMessageErrors, ThrowOnError> => (options.client ?? client).get<MailsControllerViewMessageResponses, MailsControllerViewMessageErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/msg/{id}/view',
    ...options
});

/**
 * Get the BIMI brand logo (SVG) of a message sender
 *
 * Serves the logo SVG stored with the mail during BIMI verification. Check `bimi.verified` on the message before displaying it as a trusted brand logo.
 */
export const mailsControllerBimiLogo = <ThrowOnError extends boolean = false>(options: Options<MailsControllerBimiLogoData, ThrowOnError>): RequestResult<MailsControllerBimiLogoResponses, MailsControllerBimiLogoErrors, ThrowOnError> => (options.client ?? client).get<MailsControllerBimiLogoResponses, MailsControllerBimiLogoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/msg/{id}/bimi-logo',
    ...options
});

/**
 * List the actions available on a message
 */
export const mailsControllerMessageActions = <ThrowOnError extends boolean = false>(options?: Options<MailsControllerMessageActionsData, ThrowOnError>): RequestResult<MailsControllerMessageActionsResponses, MailsControllerMessageActionsErrors, ThrowOnError> => (options?.client ?? client).get<MailsControllerMessageActionsResponses, MailsControllerMessageActionsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/msg/{id}/{act}',
    ...options
});

/**
 * Apply an action on a message
 *
 * Actions: setAsDelivered, setAsRead, setAsDone, move (requires `to` query parameter)
 */
export const mailsControllerApplyAction = <ThrowOnError extends boolean = false>(options: Options<MailsControllerApplyActionData, ThrowOnError>): RequestResult<MailsControllerApplyActionResponses, MailsControllerApplyActionErrors, ThrowOnError> => (options.client ?? client).post<MailsControllerApplyActionResponses, MailsControllerApplyActionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/msg/{id}/{act}',
    ...options
});

/**
 * Send a mail
 */
export const mailsControllerSendMessage = <ThrowOnError extends boolean = false>(options: Options<MailsControllerSendMessageData, ThrowOnError>): RequestResult<MailsControllerSendMessageResponses, MailsControllerSendMessageErrors, ThrowOnError> => (options.client ?? client).post<MailsControllerSendMessageResponses, MailsControllerSendMessageErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/msg',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete all existing mails matching the user blacklist
 */
export const mailsControllerApplyBlacklist = <ThrowOnError extends boolean = false>(options?: Options<MailsControllerApplyBlacklistData, ThrowOnError>): RequestResult<MailsControllerApplyBlacklistResponses, MailsControllerApplyBlacklistErrors, ThrowOnError> => (options?.client ?? client).post<MailsControllerApplyBlacklistResponses, MailsControllerApplyBlacklistErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/applyBlacklist',
    ...options
});

/**
 * Download a mail attachment
 */
export const attachmentsControllerGetAttachment = <ThrowOnError extends boolean = false>(options: Options<AttachmentsControllerGetAttachmentData, ThrowOnError>): RequestResult<AttachmentsControllerGetAttachmentResponses, AttachmentsControllerGetAttachmentErrors, ThrowOnError> => (options.client ?? client).get<AttachmentsControllerGetAttachmentResponses, AttachmentsControllerGetAttachmentErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/attachment/{mailId}/{contentId}',
    ...options
});

/**
 * List the folders of the authenticated user
 */
export const foldersControllerListFolders = <ThrowOnError extends boolean = false>(options?: Options<FoldersControllerListFoldersData, ThrowOnError>): RequestResult<FoldersControllerListFoldersResponses, FoldersControllerListFoldersErrors, ThrowOnError> => (options?.client ?? client).get<FoldersControllerListFoldersResponses, FoldersControllerListFoldersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/folders',
    ...options
});

/**
 * List folders of the authenticated user, grouped by read state
 */
export const foldersControllerListFoldersV2 = <ThrowOnError extends boolean = false>(options?: Options<FoldersControllerListFoldersV2Data, ThrowOnError>): RequestResult<FoldersControllerListFoldersV2Responses, FoldersControllerListFoldersV2Errors, ThrowOnError> => (options?.client ?? client).get<FoldersControllerListFoldersV2Responses, FoldersControllerListFoldersV2Errors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { name: 'Token', type: 'apiKey' }],
    url: '/v2/folders',
    ...options
});

/**
 * Receive Sendgrid event webhooks
 */
export const webhooksControllerSendgrid = <ThrowOnError extends boolean = false>(options: Options<WebhooksControllerSendgridData, ThrowOnError>): RequestResult<WebhooksControllerSendgridResponses, unknown, ThrowOnError> => (options.client ?? client).post<WebhooksControllerSendgridResponses, unknown, ThrowOnError>({
    url: '/webhooks/sendgrid',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
