// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type AuthErrorDto = {
    sorry: boolean;
    err: string;
};

export type UserMailDto = {
    name: string;
    domain: string;
    unauthorizedFolders?: Array<string>;
};

export type FolderDto = {
    name: string;
    /**
     * Number of mails in this folder
     */
    count?: number;
    /**
     * Date of the last mail in this folder (ms timestamp)
     */
    last?: number;
};

export type UserConfigDto = {
    /**
     * Web UI password
     */
    pass: string;
    mails?: Array<UserMailDto>;
    folders?: Array<FolderDto>;
    /**
     * Mail blacklist filters
     */
    mailBlacklist?: Array<{
        [key: string]: unknown;
    }>;
    apnsTokens?: Array<string>;
};

export type PushTokenDto = {
    /**
     * Device push token
     */
    token: string;
};

export type SorryResponseDto = {
    sorry: boolean;
};

export type BlacklistFromFilterDto = {
    /**
     * Sender mail address
     */
    address?: string;
    /**
     * Sender display name
     */
    name?: string;
};

export type BlacklistFilterDto = {
    /**
     * Drop incoming mails whose From matches exactly: any field set here (address, name) equal to the one of a sender. Unset fields are ignored, so `{ address }` only matches on the address.
     */
    from?: BlacklistFromFilterDto;
    /**
     * Drop incoming mails whose From contains one of the substrings set here (address or name).
     */
    fromIncludes?: BlacklistFromFilterDto;
    /**
     * Drop incoming mails whose text body (or the text derived from the html body) contains this substring.
     */
    text?: string;
    /**
     * Drop incoming mails whose subject is exactly this.
     */
    subject?: string;
    /**
     * Drop incoming mails delivered to exactly this folder.
     */
    folder?: string;
};

export type BlacklistEntryDto = {
    /**
     * Blacklist filter added to the user profile. Incoming mails matching any stored filter are dropped on arrival; `POST /applyBlacklist` deletes the already-received mails matching the filters.
     *
     * Supported criteria: `from` (exact match on the From address or name), `fromIncludes` (substring match on the From address or name), `text` (substring of the mail body), and exact match on any other top-level mail field (`subject`, `folder`, `domain`, ...).
     */
    element: BlacklistFilterDto;
};

export type MailAddressDto = {
    name?: string;
    address: string;
};

export type ConnectionPeerCertificateDto = {
    /**
     * Certificate subject fields (CN, O, ...)
     */
    subject?: {
        [key: string]: unknown;
    };
    /**
     * Certificate issuer fields
     */
    issuer?: {
        [key: string]: unknown;
    };
    valid_from?: string;
    valid_to?: string;
    fingerprint?: string;
    serialNumber?: string;
};

export type ConnectionTlsDto = {
    version?: string;
    cipher?: string;
    /**
     * Client (peer) certificate, when the sender presented one
     */
    peerCertificate?: ConnectionPeerCertificateDto;
};

export type ConnectionDto = {
    /**
     * IP of the sending connection (real client IP behind the PROXY protocol)
     */
    ip?: string;
    /**
     * Source port of the sending connection
     */
    port?: number;
    /**
     * Local port the mail was received on (25, 587 or 465)
     */
    localPort?: number;
    /**
     * Whether the connection used TLS
     */
    secure?: boolean;
    tls?: ConnectionTlsDto;
};

export type MailAttachmentDto = {
    contentId?: string;
    contentType?: string;
    fileName?: string;
    length?: number;
};

export type DkimCheckDto = {
    signingDomain?: string;
    selector?: string;
    result: 'pass' | 'fail' | 'neutral' | 'none' | 'temperror' | 'permerror' | 'policy' | 'softfail' | 'skipped';
    /**
     * Aligned signing domain, false when not aligned
     */
    aligned?: {
        [key: string]: unknown;
    };
    comment?: string;
};

export type SpfCheckDto = {
    result: 'pass' | 'fail' | 'neutral' | 'none' | 'temperror' | 'permerror' | 'policy' | 'softfail' | 'skipped';
    comment?: string;
    domain?: string;
    clientIp?: string;
};

export type DmarcCheckDto = {
    result: 'pass' | 'fail' | 'none';
    comment?: string;
};

export type BimiCertificateDto = {
    /**
     * True when the certificate chain is signed by a known VMC issuer (DigiCert, GlobalSign, SSL.com, legacy Entrust)
     */
    trusted?: boolean;
    /**
     * 'VMC' (registered mark) or 'CMC' (common mark)
     */
    type?: 'VMC' | 'CMC';
    /**
     * Certificate subject fields (CN, O, markType, ...)
     */
    subject?: {
        [key: string]: unknown;
    };
    /**
     * Domains covered by the certificate
     */
    subjectAltName?: Array<string>;
    /**
     * Certificate issuer fields
     */
    issuer?: {
        [key: string]: unknown;
    };
    validFrom?: string;
    validTo?: string;
    serialNumber?: string;
    fingerprint?: string;
};

export type BimiErrorDto = {
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * Error code (HTTP_REQUEST_FAILED, INVALID_CHAIN, INVALID_LOGO_HASH, VMC_DOMAIN_MISMATCH, SVG_VALIDATION_FAILED, ...)
     */
    code?: string;
};

export type BimiCheckDto = {
    /**
     * BIMI verification result: pass when a valid BIMI record was found for the (DMARC-passing) sender, skipped when DMARC did not pass or the policy is too lax, none when the sender publishes no record
     */
    result: 'pass' | 'fail' | 'skipped' | 'temperr' | 'none';
    comment?: string;
    /**
     * BIMI selector the record was found for
     */
    selector?: string;
    /**
     * Sender domain the BIMI record belongs to
     */
    domain?: string;
    /**
     * Raw BIMI DNS TXT record
     */
    rr?: string;
    /**
     * Logo SVG URL from the BIMI record
     */
    logoUrl?: string;
    /**
     * VMC (Verified Mark Certificate) URL from the BIMI record
     */
    authorityUrl?: string;
    /**
     * Base64 of the logo SVG, when it could be downloaded and passed the BIMI SVG validation. Excluded from the list endpoints: use GET /msg/{id} or GET /msg/{id}/bimi-logo
     */
    logo?: string;
    /**
     * True when the logo passed every check: either no VMC is published, or the VMC is valid and its embedded logo hash and domain match. Clients should only display the logo when verified
     */
    verified?: boolean;
    /**
     * Whether the downloaded logo matches the hash embedded in the VMC
     */
    logoHashMatch?: boolean;
    /**
     * Whether the sender domain is covered by the VMC
     */
    domainVerified?: boolean;
    /**
     * VMC certificate details, saved whenever they could be read, even when the chain is not signed by a known authority (check `trusted`)
     */
    certificate?: BimiCertificateDto;
    /**
     * Logo/certificate download or validation error, when any
     */
    error?: BimiErrorDto;
};

export type SpamRuleDto = {
    /**
     * SpamAssassin rule name
     */
    name: string;
    /**
     * Score added by the rule
     */
    score: number;
    description?: string;
};

export type SpamCheckDto = {
    /**
     * Total score (higher is spammier)
     */
    score: number;
    /**
     * Spam threshold
     */
    required: number;
    /**
     * score >= required
     */
    isSpam: boolean;
    /**
     * Matched rules
     */
    rules: Array<SpamRuleDto>;
};

export type MailDto = {
    /**
     * Unique time-sortable mail id (ObjectId hex string; lexicographic order matches reception time)
     */
    id: string;
    /**
     * Owner of the mail
     */
    user: string;
    domain?: string;
    folder: string;
    originalFolder?: string;
    /**
     * Reception date, unix timestamp in milliseconds
     */
    date: number;
    from?: Array<MailAddressDto>;
    envelopeTo?: Array<MailAddressDto>;
    subject?: string;
    text?: string;
    html?: string;
    /**
     * Plain-text version of the html body, computed on the fly (never stored), to fall back on when `text` is missing
     */
    htmlText?: string;
    /**
     * Connection metadata: sender IP and port, local listener port, TLS details
     */
    connection?: ConnectionDto;
    attachments?: Array<MailAttachmentDto>;
    read?: boolean;
    done?: boolean;
    delivered?: boolean;
    /**
     * DKIM verification results, one entry per signature
     */
    dkim?: Array<DkimCheckDto>;
    /**
     * SPF verification result
     */
    spf?: SpfCheckDto;
    /**
     * DMARC verification result
     */
    dmarc?: DmarcCheckDto;
    /**
     * BIMI (Brand Indicators for Message Identification) details of the sender: brand logo SVG, VMC certificate and verification results
     */
    bimi?: BimiCheckDto;
    /**
     * SpamAssassin score: Razor, Pyzor and DCC crowd networks, DNS blocklists and content rules (absent when spamd is not configured)
     */
    spam?: SpamCheckDto;
};

export type MailActionsDto = {
    actions: Array<unknown>;
};

export type SuccessResponseDto = {
    success: boolean;
};

export type SendMailDto = {
    /**
     * Sender address, must belong to the authenticated user
     */
    from: string | MailAddressDto | Array<string | MailAddressDto>;
    to?: string | MailAddressDto | Array<string | MailAddressDto>;
    cc?: string | MailAddressDto | Array<string | MailAddressDto>;
    bcc?: string | MailAddressDto | Array<string | MailAddressDto>;
    subject?: string;
    /**
     * Plain text body
     */
    text?: string;
    /**
     * HTML body
     */
    html?: string;
    /**
     * Markdown body
     */
    markdown?: string;
};

export type SendMailResultDto = {
    /**
     * The mail as accepted by the server
     */
    mail: {
        [key: string]: unknown;
    };
    folder?: string;
    /**
     * Error message when the send failed
     */
    err?: string;
    /**
     * Provider message id (sendgrid)
     */
    sendgridID?: string;
};

export type ApplyBlacklistResultDto = {
    success: boolean;
    /**
     * Number of deleted mails
     */
    deleted: number;
};

export type FoldersV2Dto = {
    /**
     * Folders with unread mails
     */
    new: Array<FolderDto>;
    /**
     * Folders with read mails
     */
    read: Array<FolderDto>;
    /**
     * Folders with done mails
     */
    done: Array<FolderDto>;
};

export type AdminForbiddenDto = {
    sorry: boolean;
    err: string;
};

export type DmarcStatsOverviewDto = {
    /**
     * Total number of stored DMARC reports
     */
    totalReports: number;
    /**
     * Total messages across all reports
     */
    totalMessages: number;
    /**
     * Messages passing DMARC (aligned DKIM or SPF)
     */
    totalPass: number;
    /**
     * Messages failing DMARC
     */
    totalFail: number;
    /**
     * Percentage of messages passing DMARC (0-100)
     */
    passRate: number;
    /**
     * Number of distinct reported domains
     */
    domainCount: number;
    /**
     * Number of distinct reporter organizations
     */
    reporterCount: number;
    /**
     * Timestamp of the first report (ms)
     */
    firstReport?: number;
    /**
     * Timestamp of the last report (ms)
     */
    lastReport?: number;
};

export type DmarcTimelineEntryDto = {
    /**
     * Day (YYYY-MM-DD)
     */
    date: string;
    /**
     * Number of reports received that day
     */
    reports: number;
    /**
     * Total messages reported that day
     */
    messages: number;
    /**
     * Messages passing DMARC that day
     */
    pass: number;
    /**
     * Messages failing DMARC that day
     */
    fail: number;
};

export type DmarcTopFailingIpDto = {
    /**
     * Source IP address
     */
    sourceIp: string;
    /**
     * Number of messages from this IP failing DMARC
     */
    failedMessages: number;
    /**
     * Number of reports mentioning this IP
     */
    reports: number;
    /**
     * Reported domains this IP failed for
     */
    domains: Array<string>;
    /**
     * Last time this IP was seen (ms timestamp)
     */
    lastSeen: number;
};

export type DmarcTopFailingDomainDto = {
    /**
     * Header-From domain
     */
    headerFrom: string;
    /**
     * Number of messages from this domain failing DMARC
     */
    failedMessages: number;
    /**
     * Number of reports mentioning this domain
     */
    reports: number;
    /**
     * Last time this domain was seen (ms timestamp)
     */
    lastSeen: number;
};

export type DmarcDomainStatsDto = {
    /**
     * Reported domain
     */
    domain: string;
    /**
     * Number of reports for this domain
     */
    reports: number;
    /**
     * Total messages reported for this domain
     */
    messages: number;
    /**
     * Messages passing DMARC
     */
    pass: number;
    /**
     * Messages failing DMARC
     */
    fail: number;
    /**
     * Pass rate percentage (0-100)
     */
    passRate: number;
    /**
     * First report timestamp (ms)
     */
    firstReport: number;
    /**
     * Last report timestamp (ms)
     */
    lastReport: number;
};

export type DmarcDispositionStatsDto = {
    /**
     * DMARC disposition applied by receivers
     */
    disposition: 'none' | 'quarantine' | 'reject';
    /**
     * Number of messages with this disposition
     */
    messages: number;
    /**
     * Number of reports containing this disposition
     */
    reports: number;
};

export type DmarcReporterStatsDto = {
    /**
     * Reporter organization name
     */
    orgName: string;
    /**
     * Number of reports sent by this reporter
     */
    reports: number;
    /**
     * Total messages across this reporter's reports
     */
    messages: number;
    /**
     * Messages passing DMARC
     */
    pass: number;
    /**
     * Number of distinct domains reported
     */
    domainCount: number;
    /**
     * First report timestamp (ms)
     */
    firstReport: number;
    /**
     * Last report timestamp (ms)
     */
    lastReport: number;
};

export type DmarcReportSummaryDto = {
    /**
     * Report id
     */
    id: string;
    /**
     * Reported domain
     */
    domain?: string;
    /**
     * Reception timestamp (ms)
     */
    receivedAt: number;
    /**
     * Mailbox the report was sent to
     */
    rcptTo: string;
    /**
     * Reporter organization name
     */
    orgName: string;
    /**
     * Report ID from the reporter
     */
    reportId: string;
    /**
     * Total messages in the report
     */
    messageCount: number;
    /**
     * Messages passing DMARC
     */
    passCount: number;
    /**
     * DMARC policy: none, quarantine or reject
     */
    policy?: string;
    /**
     * Percentage of policy applied
     */
    pct?: number;
    /**
     * Report coverage start (ms)
     */
    dateRangeBegin?: number;
    /**
     * Report coverage end (ms)
     */
    dateRangeEnd?: number;
};

export type DmarcReportListDto = {
    /**
     * Total number of stored reports
     */
    total: number;
    /**
     * Number of reports returned in this page
     */
    count: number;
    /**
     * Offset used for this page
     */
    offset: number;
    reports: Array<DmarcReportSummaryDto>;
};

export type HealthControllerHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthControllerHealthResponses = {
    /**
     * Plain text `OK`
     */
    200: string;
};

export type HealthControllerHealthResponse = HealthControllerHealthResponses[keyof HealthControllerHealthResponses];

export type UsersControllerUserConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/userConfig';
};

export type UsersControllerUserConfigErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type UsersControllerUserConfigError = UsersControllerUserConfigErrors[keyof UsersControllerUserConfigErrors];

export type UsersControllerUserConfigResponses = {
    200: UserConfigDto;
};

export type UsersControllerUserConfigResponse = UsersControllerUserConfigResponses[keyof UsersControllerUserConfigResponses];

export type UsersControllerAddFirebaseData = {
    body: PushTokenDto;
    path?: never;
    query?: never;
    url: '/addFirebase';
};

export type UsersControllerAddFirebaseErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type UsersControllerAddFirebaseError = UsersControllerAddFirebaseErrors[keyof UsersControllerAddFirebaseErrors];

export type UsersControllerAddFirebaseResponses = {
    200: SorryResponseDto;
};

export type UsersControllerAddFirebaseResponse = UsersControllerAddFirebaseResponses[keyof UsersControllerAddFirebaseResponses];

export type UsersControllerAddApnsData = {
    body: PushTokenDto;
    path?: never;
    query?: never;
    url: '/addAPNS';
};

export type UsersControllerAddApnsErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type UsersControllerAddApnsError = UsersControllerAddApnsErrors[keyof UsersControllerAddApnsErrors];

export type UsersControllerAddApnsResponses = {
    200: SorryResponseDto;
};

export type UsersControllerAddApnsResponse = UsersControllerAddApnsResponses[keyof UsersControllerAddApnsResponses];

export type UsersControllerAddBlacklistData = {
    body: BlacklistEntryDto;
    path?: never;
    query?: never;
    url: '/blacklist';
};

export type UsersControllerAddBlacklistErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type UsersControllerAddBlacklistError = UsersControllerAddBlacklistErrors[keyof UsersControllerAddBlacklistErrors];

export type UsersControllerAddBlacklistResponses = {
    200: SorryResponseDto;
};

export type UsersControllerAddBlacklistResponse = UsersControllerAddBlacklistResponses[keyof UsersControllerAddBlacklistResponses];

export type MailsControllerListMessagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of messages to return
         */
        nb?: string;
        /**
         * Timestamp cursor, combined with `direction`
         */
        from?: string;
        /**
         * Direction of the listing relative to `from`
         */
        direction?: 'past' | 'future';
        category?: 'new' | 'read' | 'done';
        /**
         * Folder to list
         */
        folder?: string;
    };
    url: '/msgs';
};

export type MailsControllerListMessagesErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type MailsControllerListMessagesError = MailsControllerListMessagesErrors[keyof MailsControllerListMessagesErrors];

export type MailsControllerListMessagesResponses = {
    200: Array<MailDto>;
};

export type MailsControllerListMessagesResponse = MailsControllerListMessagesResponses[keyof MailsControllerListMessagesResponses];

export type MailsControllerListSentMessagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of messages to return
         */
        nb?: string;
        /**
         * Timestamp cursor, combined with `direction`
         */
        from?: string;
        /**
         * Direction of the listing relative to `from`
         */
        direction?: 'past' | 'future';
        category?: 'new' | 'read' | 'done';
        /**
         * Folder to list
         */
        folder?: string;
    };
    url: '/msgs/sent';
};

export type MailsControllerListSentMessagesErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type MailsControllerListSentMessagesError = MailsControllerListSentMessagesErrors[keyof MailsControllerListSentMessagesErrors];

export type MailsControllerListSentMessagesResponses = {
    200: Array<MailDto>;
};

export type MailsControllerListSentMessagesResponse = MailsControllerListSentMessagesResponses[keyof MailsControllerListSentMessagesResponses];

export type MailsControllerListMessagesByFolderData = {
    body?: never;
    path: {
        category: 'new' | 'read' | 'done';
        folder: string;
    };
    query?: {
        /**
         * Maximum number of messages to return
         */
        nb?: string;
        /**
         * Timestamp cursor, combined with `direction`
         */
        from?: string;
        /**
         * Direction of the listing relative to `from`
         */
        direction?: 'past' | 'future';
    };
    url: '/msgs/{category}/{folder}';
};

export type MailsControllerListMessagesByFolderErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type MailsControllerListMessagesByFolderError = MailsControllerListMessagesByFolderErrors[keyof MailsControllerListMessagesByFolderErrors];

export type MailsControllerListMessagesByFolderResponses = {
    200: Array<MailDto>;
};

export type MailsControllerListMessagesByFolderResponse = MailsControllerListMessagesByFolderResponses[keyof MailsControllerListMessagesByFolderResponses];

export type MailsControllerGetMessageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/msg/{id}';
};

export type MailsControllerGetMessageErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type MailsControllerGetMessageError = MailsControllerGetMessageErrors[keyof MailsControllerGetMessageErrors];

export type MailsControllerGetMessageResponses = {
    200: MailDto;
};

export type MailsControllerGetMessageResponse = MailsControllerGetMessageResponses[keyof MailsControllerGetMessageResponses];

export type MailsControllerViewMessageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/msg/{id}/view';
};

export type MailsControllerViewMessageErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type MailsControllerViewMessageError = MailsControllerViewMessageErrors[keyof MailsControllerViewMessageErrors];

export type MailsControllerViewMessageResponses = {
    /**
     * Raw HTML (or text) body of the message
     */
    200: string;
};

export type MailsControllerViewMessageResponse = MailsControllerViewMessageResponses[keyof MailsControllerViewMessageResponses];

export type MailsControllerBimiLogoData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/msg/{id}/bimi-logo';
};

export type MailsControllerBimiLogoErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
    /**
     * Mail or BIMI logo not found
     */
    404: unknown;
};

export type MailsControllerBimiLogoError = MailsControllerBimiLogoErrors[keyof MailsControllerBimiLogoErrors];

export type MailsControllerBimiLogoResponses = {
    /**
     * BIMI logo SVG
     */
    200: Blob | File;
};

export type MailsControllerBimiLogoResponse = MailsControllerBimiLogoResponses[keyof MailsControllerBimiLogoResponses];

export type MailsControllerMessageActionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/msg/{id}/{act}';
};

export type MailsControllerMessageActionsErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type MailsControllerMessageActionsError = MailsControllerMessageActionsErrors[keyof MailsControllerMessageActionsErrors];

export type MailsControllerMessageActionsResponses = {
    200: MailActionsDto;
};

export type MailsControllerMessageActionsResponse = MailsControllerMessageActionsResponses[keyof MailsControllerMessageActionsResponses];

export type MailsControllerApplyActionData = {
    body?: never;
    path: {
        id: string;
        act: 'setAsDelivered' | 'setAsRead' | 'setAsDone' | 'move';
    };
    query?: {
        /**
         * Target folder for the move action
         */
        to?: string;
    };
    url: '/msg/{id}/{act}';
};

export type MailsControllerApplyActionErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type MailsControllerApplyActionError = MailsControllerApplyActionErrors[keyof MailsControllerApplyActionErrors];

export type MailsControllerApplyActionResponses = {
    200: SuccessResponseDto;
};

export type MailsControllerApplyActionResponse = MailsControllerApplyActionResponses[keyof MailsControllerApplyActionResponses];

export type MailsControllerSendMessageData = {
    body: SendMailDto;
    path?: never;
    query?: never;
    url: '/msg';
};

export type MailsControllerSendMessageErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type MailsControllerSendMessageError = MailsControllerSendMessageErrors[keyof MailsControllerSendMessageErrors];

export type MailsControllerSendMessageResponses = {
    200: SendMailResultDto;
};

export type MailsControllerSendMessageResponse = MailsControllerSendMessageResponses[keyof MailsControllerSendMessageResponses];

export type MailsControllerApplyBlacklistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/applyBlacklist';
};

export type MailsControllerApplyBlacklistErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type MailsControllerApplyBlacklistError = MailsControllerApplyBlacklistErrors[keyof MailsControllerApplyBlacklistErrors];

export type MailsControllerApplyBlacklistResponses = {
    200: ApplyBlacklistResultDto;
};

export type MailsControllerApplyBlacklistResponse = MailsControllerApplyBlacklistResponses[keyof MailsControllerApplyBlacklistResponses];

export type AttachmentsControllerGetAttachmentData = {
    body?: never;
    path: {
        mailId: string;
        contentId: string;
    };
    query?: never;
    url: '/attachment/{mailId}/{contentId}';
};

export type AttachmentsControllerGetAttachmentErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
    /**
     * Mail or attachment not found
     */
    404: unknown;
};

export type AttachmentsControllerGetAttachmentError = AttachmentsControllerGetAttachmentErrors[keyof AttachmentsControllerGetAttachmentErrors];

export type AttachmentsControllerGetAttachmentResponses = {
    /**
     * Attachment content
     */
    200: Blob | File;
};

export type AttachmentsControllerGetAttachmentResponse = AttachmentsControllerGetAttachmentResponses[keyof AttachmentsControllerGetAttachmentResponses];

export type FoldersControllerListFoldersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/folders';
};

export type FoldersControllerListFoldersErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type FoldersControllerListFoldersError = FoldersControllerListFoldersErrors[keyof FoldersControllerListFoldersErrors];

export type FoldersControllerListFoldersResponses = {
    200: Array<FolderDto>;
};

export type FoldersControllerListFoldersResponse = FoldersControllerListFoldersResponses[keyof FoldersControllerListFoldersResponses];

export type FoldersControllerListFoldersV2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/folders';
};

export type FoldersControllerListFoldersV2Errors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
};

export type FoldersControllerListFoldersV2Error = FoldersControllerListFoldersV2Errors[keyof FoldersControllerListFoldersV2Errors];

export type FoldersControllerListFoldersV2Responses = {
    200: FoldersV2Dto;
};

export type FoldersControllerListFoldersV2Response = FoldersControllerListFoldersV2Responses[keyof FoldersControllerListFoldersV2Responses];

export type WebhooksControllerSendgridData = {
    body: Array<string>;
    path?: never;
    query?: never;
    url: '/webhooks/sendgrid';
};

export type WebhooksControllerSendgridResponses = {
    /**
     * Events accepted (empty body)
     */
    200: unknown;
};

export type DmarcStatsControllerGetOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/dmarc/overview';
};

export type DmarcStatsControllerGetOverviewErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
    /**
     * Authenticated but not an admin user
     */
    403: AdminForbiddenDto;
};

export type DmarcStatsControllerGetOverviewError = DmarcStatsControllerGetOverviewErrors[keyof DmarcStatsControllerGetOverviewErrors];

export type DmarcStatsControllerGetOverviewResponses = {
    200: DmarcStatsOverviewDto;
};

export type DmarcStatsControllerGetOverviewResponse = DmarcStatsControllerGetOverviewResponses[keyof DmarcStatsControllerGetOverviewResponses];

export type DmarcStatsControllerGetTimelineData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of days to include (default 30, max 365)
         */
        days?: number;
    };
    url: '/admin/dmarc/timeline';
};

export type DmarcStatsControllerGetTimelineErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
    /**
     * Authenticated but not an admin user
     */
    403: AdminForbiddenDto;
};

export type DmarcStatsControllerGetTimelineError = DmarcStatsControllerGetTimelineErrors[keyof DmarcStatsControllerGetTimelineErrors];

export type DmarcStatsControllerGetTimelineResponses = {
    200: Array<DmarcTimelineEntryDto>;
};

export type DmarcStatsControllerGetTimelineResponse = DmarcStatsControllerGetTimelineResponses[keyof DmarcStatsControllerGetTimelineResponses];

export type DmarcStatsControllerGetTopFailingIpsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of IPs to return (default 20, max 100)
         */
        limit?: number;
    };
    url: '/admin/dmarc/top-failing-ips';
};

export type DmarcStatsControllerGetTopFailingIpsErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
    /**
     * Authenticated but not an admin user
     */
    403: AdminForbiddenDto;
};

export type DmarcStatsControllerGetTopFailingIpsError = DmarcStatsControllerGetTopFailingIpsErrors[keyof DmarcStatsControllerGetTopFailingIpsErrors];

export type DmarcStatsControllerGetTopFailingIpsResponses = {
    200: Array<DmarcTopFailingIpDto>;
};

export type DmarcStatsControllerGetTopFailingIpsResponse = DmarcStatsControllerGetTopFailingIpsResponses[keyof DmarcStatsControllerGetTopFailingIpsResponses];

export type DmarcStatsControllerGetTopFailingDomainsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of domains to return (default 20, max 100)
         */
        limit?: number;
    };
    url: '/admin/dmarc/top-failing-domains';
};

export type DmarcStatsControllerGetTopFailingDomainsErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
    /**
     * Authenticated but not an admin user
     */
    403: AdminForbiddenDto;
};

export type DmarcStatsControllerGetTopFailingDomainsError = DmarcStatsControllerGetTopFailingDomainsErrors[keyof DmarcStatsControllerGetTopFailingDomainsErrors];

export type DmarcStatsControllerGetTopFailingDomainsResponses = {
    200: Array<DmarcTopFailingDomainDto>;
};

export type DmarcStatsControllerGetTopFailingDomainsResponse = DmarcStatsControllerGetTopFailingDomainsResponses[keyof DmarcStatsControllerGetTopFailingDomainsResponses];

export type DmarcStatsControllerGetDomainStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/dmarc/domains';
};

export type DmarcStatsControllerGetDomainStatsErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
    /**
     * Authenticated but not an admin user
     */
    403: AdminForbiddenDto;
};

export type DmarcStatsControllerGetDomainStatsError = DmarcStatsControllerGetDomainStatsErrors[keyof DmarcStatsControllerGetDomainStatsErrors];

export type DmarcStatsControllerGetDomainStatsResponses = {
    200: Array<DmarcDomainStatsDto>;
};

export type DmarcStatsControllerGetDomainStatsResponse = DmarcStatsControllerGetDomainStatsResponses[keyof DmarcStatsControllerGetDomainStatsResponses];

export type DmarcStatsControllerGetDispositionStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/dmarc/dispositions';
};

export type DmarcStatsControllerGetDispositionStatsErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
    /**
     * Authenticated but not an admin user
     */
    403: AdminForbiddenDto;
};

export type DmarcStatsControllerGetDispositionStatsError = DmarcStatsControllerGetDispositionStatsErrors[keyof DmarcStatsControllerGetDispositionStatsErrors];

export type DmarcStatsControllerGetDispositionStatsResponses = {
    200: Array<DmarcDispositionStatsDto>;
};

export type DmarcStatsControllerGetDispositionStatsResponse = DmarcStatsControllerGetDispositionStatsResponses[keyof DmarcStatsControllerGetDispositionStatsResponses];

export type DmarcStatsControllerGetReporterStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/dmarc/reporters';
};

export type DmarcStatsControllerGetReporterStatsErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
    /**
     * Authenticated but not an admin user
     */
    403: AdminForbiddenDto;
};

export type DmarcStatsControllerGetReporterStatsError = DmarcStatsControllerGetReporterStatsErrors[keyof DmarcStatsControllerGetReporterStatsErrors];

export type DmarcStatsControllerGetReporterStatsResponses = {
    200: Array<DmarcReporterStatsDto>;
};

export type DmarcStatsControllerGetReporterStatsResponse = DmarcStatsControllerGetReporterStatsResponses[keyof DmarcStatsControllerGetReporterStatsResponses];

export type DmarcStatsControllerGetRecentReportsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page size (default 50, max 200)
         */
        limit?: number;
        /**
         * Number of reports to skip (default 0)
         */
        offset?: number;
    };
    url: '/admin/dmarc/reports';
};

export type DmarcStatsControllerGetRecentReportsErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
    /**
     * Authenticated but not an admin user
     */
    403: AdminForbiddenDto;
};

export type DmarcStatsControllerGetRecentReportsError = DmarcStatsControllerGetRecentReportsErrors[keyof DmarcStatsControllerGetRecentReportsErrors];

export type DmarcStatsControllerGetRecentReportsResponses = {
    200: DmarcReportListDto;
};

export type DmarcStatsControllerGetRecentReportsResponse = DmarcStatsControllerGetRecentReportsResponses[keyof DmarcStatsControllerGetRecentReportsResponses];

export type DmarcStatsControllerGetReportByIdData = {
    body?: never;
    path: {
        /**
         * Report id
         */
        id: string;
    };
    query?: never;
    url: '/admin/dmarc/reports/{id}';
};

export type DmarcStatsControllerGetReportByIdErrors = {
    /**
     * Missing or invalid token
     */
    400: AuthErrorDto;
    /**
     * Authenticated but not an admin user
     */
    403: AdminForbiddenDto;
};

export type DmarcStatsControllerGetReportByIdError = DmarcStatsControllerGetReportByIdErrors[keyof DmarcStatsControllerGetReportByIdErrors];

export type DmarcStatsControllerGetReportByIdResponses = {
    /**
     * The full DMARC report
     */
    200: unknown;
};
